blueprint:
  name: Doorbell Notification with Camera Snapshot
  description: 'This automation blueprint creates a camera snapshot when the doorbell
    rings and sends a notification to a devices with the picture.'
  domain: automation
  source_url: 
  input:
    binary_sensor:
      name: Push button
      description: Entity representing a physical push button (which restores its
        position when released). It must emit a square signal on press. This automation
        is triggered by its falling edge.
      selector:
        entity:
          domain: binary_sensor
          integration: esphome
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain: camera
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications
      selector:
        device:
          integration: mobile_app
    is_ios:
      name: Is it an iOS device?
      description: Toggle if your selected device runs iOS, default is Android
      selector:
        boolean: {}
      default: false
    notification_title:
      name: Notification title (Optional)
      description: 'Default: "The doorbell was rung!"'
      default: The doorbell was rung!
    notification_message:
      name: Notification message (Optional)
      description: 'Default: "{{ binary_sensor_name }} was activated!"'
      default: '{{ binary_sensor_name }} was activated!'
    delay_start:
      name: Delay (Optional)
      description: Wait before creating camera snapshot
      default: 0.0
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    mode:
      name: Mode
      description: The mode of the automation
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel
          mode: dropdown
      default: single
    throttle_time:
      name: Throttle time (Optional)
      description: Time to wait before the automation can trigger again
      default: 0.0
      selector:
        number:
          min: 0.0
          max: 300.0
          unit_of_measurement: seconds
          mode: slider
          step: 5.0
trigger:
  platform: state
  entity_id: !input 'binary_sensor'
  from: 'off'
  to: 'on'
variables:
  binary_sensor: !input 'binary_sensor'
  binary_sensor_name: '{{ states[binary_sensor].name }}'
  camera: !input 'camera'
  notify_device: !input 'notify_device'
  is_ios: !input 'is_ios'
  notification_title: !input 'notification_title'
  notification_message: !input 'notification_message'
  delay_start: !input 'delay_start'
  throttle_time: !input 'throttle_time'
  snapshot_create_file_path: /config/www/tmp/snapshot_{{ states[camera].object_id
    }}.jpg
  snapshot_access_file_path: '{{ snapshot_create_file_path | replace(''/config/www'',''/local'')
    }}'
mode: !input 'mode'
action:
- delay: '{{ delay_start }}'
- service: camera.snapshot
  entity_id: !input 'camera'
  data:
    filename: '{{ snapshot_create_file_path }}'
- device_id: !input 'notify_device'
  domain: mobile_app
  type: notify
  title: '{{ notification_title }}'
  message: '{{ notification_message }}'
  data: >
    {% set android_data = {
      "image": "%s",
      "clickAction": "/dashboard-cams"
    } | format(snapshot_access_file_path) %}
    {% set ios_data = {
      "attachment": {
        "url": "%s",
        "content_type": "JPEG"
      },
      "clickAction": "/dashboard-cams"
    } | format(snapshot_access_file_path) %}
    {{ ios_data if is_ios else android_data }}
- delay: '{{ throttle_time }}'